### ISSUE TITLE
Error in compiling wikitrivia.py 

### ISSUE THREAD

**Issue by stevennx** [nshdesai/Amax#1]
After moving wikitrivia.py and article.py in the same directory as codexyz, compiler could not locate Article module

Expected time to finish ~15 mins after @nshdesai debugs the code

**Comment by nshdesai** [comment]
Check functionality after [this commit](https://github.com/nshdesai/Amax/commit/b556f6723d26a5c3ff5e7ffa3ad70088f21d20de)

**Comment by stevennx** [comment]
Will close issue, codexyz abandoned
